import { type NextPage } from "next";
import Head from "next/head";
import { Navigation } from "~/components/Navigation";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>TypeCafe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
      </main>
    </>
  );
};

export default Home;
